#mqtt:
#  broker-url: tcp://localhost:1883
---
spring:
  config:    activate:      on-profile:      - default

mqtt:
  broker-url: tcp://localhost:1883
  username: user1
  password: hm93bqCj6xR562U
  topic-filter: request/echo

---
spring:
  config:
    activate:
      on-profile:
      - docker-compose
      
mqtt:
  broker-url: tcp://hivemq:1883
  username: user1
  password: hm93bqCj6xR562U
  topic-filter: request/echo      