simple-echo:
  client-id: springboot_paho_${random.value}
  topic-filter: request/echo

measure-latency:
  client-id: springboot_paho_${random.value}
  topic: measure/latency
  fixed-rate: 1000
  
---
spring:
  config:    activate:      on-profile:      - default

mqtt:
  broker-url: tcp://localhost:1883
  username: user1
  password: hm93bqCj6xR562U

---
spring:
  config:
    activate:
      on-profile:
      - docker-compose
      
mqtt:
  broker-url: tcp://hivemq:1883
  username: user1
  password: hm93bqCj6xR562U
  
measure-latency:
  fixed-rate: 500  
   