apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod-issuer
  namespace: default
spec:
  acme:
    email: kwonghung.yip@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-priv-key-secret
    solvers:
    - http01:
        ingress:
          class: haproxy

---
apiVersion: v1
kind: Secret
metadata:
  name: letsencrypt-prod-keystore-secret
  namespace: default
type: Opaque
data:
  jks-password: Y2hhbmdlaXQ=
  p12-password: Y2hhbmdlaXQ=

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-prod-cert
  namespace: default
spec:
  issuerRef:
    name: letsencrypt-prod-issuer
    kind: Issuer
  secretName: letsencrypt-prod-secret
  commonName: kwonghung-yip.asuscomm.com
  dnsNames:
  - kwonghung-yip.asuscomm.com

  keystores:
    jks:
      create: true
      passwordSecretRef:
        key: jks-password
        name: letsencrypt-prod-keystore-secret
    pkcs12:
      create: true
      passwordSecretRef:
        key: p12-password
        name: letsencrypt-prod-keystore-secret

