apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-staging-issuer
  namespace: default
spec:
  acme:
    email: kwonghung.yip@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging-priv-key-secret
    solvers:
    - http01:
        ingress:
          class: haproxy

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-staging-cert
  namespace: default
spec:
  issuerRef:
    name: letsencrypt-staging-issuer
    kind: Issuer
  secretName: letsencrypt-staging-secret
  commonName: kwonghung-yip.asuscomm.com
  dnsNames:
  - kwonghung-yip.asuscomm.com

