<<<<<<< HEAD
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
spec:
  rules:
    - host: kwonghung-yip.asuscomm.com
      http:  
        paths:
          - path: /
            backend:
              serviceName: nginxx-service
              servicePort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: ClusterIP
  selector:
    app: nginx
    ver: 1.21
  ports:
  - name: http
    port: 80
  - name: https
    port: 443

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
      ver: 1.21
  template:
    metadata:
      labels:
        app: nginx
        ver: 1.21
    spec:
      containers:
      - name: nginx
        image: docker.io/nginx:1.21
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
=======
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    kubernetes.io/ingress.class: haproxy
spec:
  tls:
    - hosts:
      - kwonghung-yip.asuscomm.com
      secretName: letsencrypt-prod-secret
  rules:
  - host: kwonghung-yip.asuscomm.com
    http:  
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port: 
              number: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: ClusterIP
  selector:
    app: nginx
    ver: "1.21"
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
      ver: "1.21"
  template:
    metadata:
      labels:
        app: nginx
        ver: "1.21"
    spec:
      containers:
      - name: nginx
        image: docker.io/nginx:1.21
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        volumeMounts:
          - name: nginx-content
            mountPath: /usr/share/nginx/my-content
          - name: nginx-config
            mountPath: /etc/nginx/conf.d
      volumes:
      - name: nginx-content
        configMap:
          name: nginx-content 
      - name: nginx-config
        configMap:
          name: nginx-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-content
data:
  test.txt: |
    Test page for kwonghung-yip.asuscomm.com

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
      listen 80;
      listen [::]:80;
      server_name localhost;

      location / {
        root  /usr/share/nginx/my-content;
        index index.html index.htm;
      }

      error_page 500 502 503 /50x.html;
      location = /50x.html {
        root /usr/share/nginx/html;
      }
    }


>>>>>>> 0a51ffd081f61818fe56df5a1f3197dded650c45
